### ISSUE TITLE
[FR] Add specific world

### ISSUE THREAD

**Issue by UnEnanoMas** [Prim69/FakePlayers#2]
It is very well done, I would like it to be able to be executed in a specific world in order to prevent other players from spawning it in other worlds.

For example to put a world of PracticePvP and practice combos

**Comment by HashimTheArab** [comment]
Players need the permission to use the command so if you're using pureperms you can just set that to the specific world /setuperm PlayerName fakeplayer.spawn PracticePvP 

/setuperm <player> <permission> [world]
